name: Lambda_creation
on: 
  push:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  Script-Install:
    runs-on: ubuntu-latest
    steps:
      - name: fetch aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::001957572041:role/Github
          aws-region: ap-south-1
      - name: fetching the script
        uses: actions/checkout@v4
      - name: terraform installation
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "latest"     
      - name: terraform init
        run: terraform init
      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            .terraform
            .terraform.lock.hcl
          key: terraform-${{ runner.os }}-${{ hashFiles('**/*.tf') }}
        
  Validate:
    needs: Script-Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            .terraform
            .terraform.lock.hcl
          key: terraform-${{ runner.os }}-${{ hashFiles('**/*.tf') }}
      - name: terraform Validate
        run: terraform validate

  Trivy:
    needs: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            .terraform
            .terraform.lock.hcl
          key: terraform-${{ runner.os }}-${{ hashFiles('**/*.tf') }}
      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: config
          scan-ref: .
          severity: HIGH,CRITICAL
          exit-code: 1
        
  Plan:
    needs: Trivy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            .terraform
            .terraform.lock.hcl
          key: terraform-${{ runner.os }}-${{ hashFiles('**/*.tf') }}
      - name: terraform plan
        run: terraform plan

  apply:
    needs: Plan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            .terraform
            .terraform.lock.hcl
          key: terraform-${{ runner.os }}-${{ hashFiles('**/*.tf') }}
      - name: terraform apply
        run: terraform apply -auto-approve
      
      
        
  
